### ISSUE TITLE
DiverseMath23K

### ISSUE THREAD

**Issue by ghost** [zhouzihao501/DiverseMWP#1]
Hi, have you considered releasing your dataset to the public?

**Comment by zhouzihao501** [comment]
> 

Hi, thanks for your interest. Recently, we work on replacing filter from MWP-Bert to ChatGPT. In such way, we can get a higher quality DiverseMath23k and detailed reasoning process for each MWP. Hence, we will release it after we finsh this replacement. Thanks!
